/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#43474a',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#73787b',
        'outline-variant': '#c3c7cb',
        'surface-tint': '#526069',
        'primary': '#526069',
        'on-primary': '#ffffff',
        'primary-container': '#e3f2fd',
        'on-primary-container': '#606f78',
        'inverse-primary': '#bac9d3',
        'secondary': '#5e5e5f',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0dfdf',
        'on-secondary-container': '#626363',
        'tertiary': '#5d5f5f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#f0f0f0',
        'on-tertiary-container': '#6c6d6d',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        base: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
      },
      fontFamily: {
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        'h1': ['Inter', 'system-ui', 'sans-serif'],
        'h2': ['Inter', 'system-ui', 'sans-serif'],
        'h3': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'h3': ['20px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '600' }],
        'h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h1': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
