import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import MaterialIcon from '@/components/MaterialIcon';
export default function MediaHubPage() {
    const categories = ['All', 'Temples', 'Architectural', 'Cultural Events', 'Testimonials', 'Behind the Scenes'];
    const media = [
        { id: 1, title: 'Palitana Temples at Sunrise', category: 'Temples', type: 'image' },
        { id: 2, title: 'Jain Architecture Documentary', category: 'Cultural Events', type: 'video' },
        { id: 3, title: 'Community Volunteer Stories', category: 'Testimonials', type: 'video' },
        { id: 4, title: 'Temple Restoration Project', category: 'Behind the Scenes', type: 'image' },
        { id: 5, title: 'Ancient Manuscript Collection', category: 'Architectural', type: 'image' },
        { id: 6, title: 'Heritage Conservation Webinar', category: 'Cultural Events', type: 'video' },
    ];
    return (_jsx("div", { className: "w-full", children: _jsxs("div", { className: "max-w-7xl mx-auto px-lg py-xl", children: [_jsxs("div", { className: "mb-xl", children: [_jsx("h1", { className: "font-h1 text-h1 text-on-surface mb-md", children: "Media Hub" }), _jsx("p", { className: "font-body-lg text-body-lg text-on-surface-variant", children: "Explore our collection of photos, videos, and documentaries showcasing Jain heritage." })] }), _jsx("div", { className: "flex gap-md overflow-x-auto no-scrollbar mb-lg pb-sm", children: categories.map((cat) => (_jsx("button", { className: `px-lg py-sm rounded-full font-label-sm text-label-sm whitespace-nowrap transition-colors ${cat === 'All'
                            ? 'bg-primary text-on-primary'
                            : 'bg-surface-container border border-outline-variant text-on-surface hover:border-outline'}`, children: cat }, cat))) }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-md", children: media.map((item) => (_jsxs("div", { className: "group rounded-lg overflow-hidden border border-outline-variant hover:border-outline transition-all cursor-pointer", children: [_jsx("div", { className: "relative h-48 bg-surface-container overflow-hidden", children: _jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-primary/20 to-transparent group-hover:from-primary/40 transition-all flex items-center justify-center", children: _jsx(MaterialIcon, { name: item.type === 'video' ? 'play_circle' : 'image', size: 48, className: "text-on-surface opacity-70 group-hover:opacity-100 transition-opacity" }) }) }), _jsxs("div", { className: "p-md bg-surface-container-lowest", children: [_jsx("p", { className: "font-label-caps text-label-caps text-primary mb-xs", children: item.category }), _jsx("h3", { className: "font-h3 text-h3 text-on-surface group-hover:text-primary transition-colors", children: item.title })] })] }, item.id))) }), _jsx("div", { className: "mt-xl bg-primary-container border border-outline-variant rounded-xl p-lg", children: _jsxs("div", { className: "flex items-center gap-md", children: [_jsx("div", { className: "p-lg bg-primary rounded-lg text-on-primary flex-shrink-0", children: _jsx(MaterialIcon, { name: "upload", size: 24 }) }), _jsxs("div", { className: "flex-1", children: [_jsx("h2", { className: "font-h2 text-h2 text-on-surface mb-sm", children: "Share Your Media" }), _jsx("p", { className: "font-body-md text-body-md text-on-surface-variant", children: "Help document Jain heritage by uploading your photos and videos" })] }), _jsx("button", { className: "btn-primary flex-shrink-0", children: "Upload Media" })] }) })] }) }));
}
